import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';



import 'main.dart';


class Normal extends StatelessWidget {

   final Function numbers,functions,animate,cancel,dotc;
   Normal(this.numbers , this.functions , this.animate , this.cancel , this.dotc);


  @override
  Widget build(BuildContext context) {
   return Container(color: Colors.deepOrange, height:MediaQuery.of(context).size.width*1.25 ,
       child: Row(crossAxisAlignment: CrossAxisAlignment.stretch,   children: <Widget>[
          Expanded(child:  Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: <Widget>[Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)), color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent, child: Text("cancel" ,style: TextStyle(color: Colors.deepOrange, fontSize: 15),), onPressed:  (){ cancel(); },))) ,   Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("7"  ,style: TextStyle(color: Colors.deepOrange , fontSize: 30),), onPressed:  (){ numbers("7"); }, ))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("4" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("4"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("1" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("1"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: FlutterLogo(),onPressed:  (){ animate(); },))) , ],),),
          Expanded(child:  Column(crossAxisAlignment: CrossAxisAlignment.stretch,children: <Widget>[Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton( shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)), color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("back" ,style: TextStyle(color: Colors.deepOrange, fontSize: 15),), onPressed:  (){ functions("back"); },))) ,   Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("8"  ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),), onPressed:  (){ numbers("8"); }, ))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("5" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("5"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("2" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("2"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("0" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("0"); },))) , ],),),
          Expanded(child:  Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: <Widget>[Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("%" ,style: TextStyle(color: Colors.deepOrange, fontSize: 20),), onPressed:  (){ functions("%"); },))) ,   Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("9"  ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),), onPressed:  (){ numbers("9"); }, ))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("6" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("6"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("3" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ numbers("3"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("." ,style: TextStyle(color: Colors.deepOrange, fontSize: 20),),onPressed:  (){ dotc(); },))) , ],),),
          Expanded(child:  Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: <Widget>[Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("/" ,style: TextStyle(color: Colors.deepOrange, fontSize: 20),), onPressed:  (){ functions("/"); },))) ,   Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("x"  ,style: TextStyle(color: Colors.deepOrange, fontSize: 20),), onPressed:  (){ functions("*"); }, ))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("-" ,style: TextStyle(color: Colors.deepOrange, fontSize: 30),),onPressed:  (){ functions("-"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("+" ,style: TextStyle(color: Colors.deepOrange, fontSize: 20),),onPressed:  (){ functions("+"); },))) ,Expanded( child :  Container(padding : EdgeInsets.all(0.1),child: FlatButton(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(0)),color: Colors.black, splashColor: Colors.transparent,highlightColor: Colors.transparent,child: Text("=" ,style: TextStyle(color: Colors.deepOrange, fontSize: 20),),onPressed:  (){ functions("="); },))) , ],),),
   ],
   )


   );
  }
}
